### ISSUE TITLE
verify_expiration has been totally removed

### ISSUE THREAD

**Issue by cancan101** [jpadilla/pyjwt#147]
It was here: https://github.com/jpadilla/pyjwt/blob/8f28b4a6124830fcea400668840e645bb91e38a2/jwt/api.py#L184
and now I see no mention of its removal / deprecation any docs, etc.

The only mention I see is:
>You can turn off expiration time verification with the verify_expiration argument.

**Comment by mark-adams** [comment]
Yea, it looks like we missed that one. Using `{'verify_expiration': False}` for options should have the same effect. I submitted a PR to fix the README and CHANGELOG.

Thanks for raising the issue!

**Comment by cancan101** [comment]
I do not think just adding a note to the docs is the right move.
At the very least the old parameter should be marked as deprecated and converted to the new parameter for at least one version.

**Comment by mark-adams** [comment]
That's exactly what we did with the `verify` parameter to decode() since we would like to eliminate it at a later point. Our behavior with the deprecation of the verify parameter is very intentional and well documented (both in the CHANGELOG and using warnings)

The removal of `verify_expiration` is certainly something we wanted to do (for the same reasons we want to remove `verify`), but the actual removal of that parameter in the last release (instead of proper deprecation) slipped by us when we reviewed the PR.

At this point, I'm not sure I'm behind a knee-jerk restoration of the `verify_expiration` parameter since we already ripped the band-aid off. The only negative consequence is that the very few (probably) users who are using that parameter will run into verification issues if they are trying to decode an expired token. In other words, we're actually being a bit more secure. If things were the other way around and the removal of the parameter actually hurt security, I would not be opposed to bringing it back and making another release.

Unless others have a compelling argument, I'm for leaving it as is but documenting the change instead of making another release and having this weird "now its gone; now its back" thing going on.

@jpadilla, your thoughts?

**Comment by cancan101** [comment]
The "few" users include @jpadilla's django-rest-framework-jwt which has not been updated.
Further one of the issues is that the that [`kwargs` is captured and then silently dropped](https://github.com/jpadilla/pyjwt/blob/ddbaf0008eac6559da5ebd1f24f68ee99ccb34b0/jwt/api_jwt.py#L76) which is annoying when debugging / dealing with mispelled params.

**Comment by mark-adams** [comment]
Now I definitely agree with you there, I don't like our usage of **kwargs currently and I think that's something we should remove in a future release.

I'm sure @jpadilla would probably agree that django-rest-framework-jwt should be updated as well :-)

**Comment by cancan101** [comment]
Sure, and I filed this: https://github.com/GetBlimp/django-rest-framework-jwt/issues/103 but I don't think that a breaking API change should just be left out there. I'm not sure how true to http://semver.org/ you aim to be, but we still can fix the breaking API change.

**Comment by mark-adams** [comment]
@cancan101 Good point. You've won me over. I don't feel that strongly about it. :+1: 

If you'd like to make a PR adding the parameter back and introducing some tests as well as deprecation warnings, please go ahead. If not, I'll probably do Friday or Saturday and then we can make another release this weekend.

**Comment by lucacorti** [comment]
As a temporary workaround, is it possible to downgrade to PyJWT 1.0.1 to disable expiration verification with djangorestramework-jwt? Any security issue with that?

ATM I'm stuck with disabling verification altogether, which is obviously not good.

**Comment by mark-adams** [comment]
This was fixed in the [v1.2 release](https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.md#v120)

Please upgrade.
