### ISSUE TITLE
ES256 not supported?

### ISSUE THREAD

**Issue by shea256** [jpadilla/pyjwt#151]
Hey guys!

For some reason I'm no longer able to get ES256 to work, but it was working for me earlier.

Here's the code:

```python
import jwt, ecdsa

signing_pem = SigningKey.generate().to_pem()
payload = {"some": "example"}
signed_token = jwt.encode(payload, signing_pem, algorithm='ES256')
```

And it yields the following error:

> raise NotImplementedError('Algorithm not supported')

*(for reference, I have version 1.1.0 installed)*

Was support for ES256 discontinued? Am I doing something wrong?

Thanks!

**Comment by mark-adams** [comment]
Previously, PyCrypto was required for RSA and ecdsa was required for EC algorithms. Back in December, we switched to using `cryptography` instead of those libraries because it provided both sets of algorithms (RSA and EC) in a single library and also had better performance.

Please make sure you have installed `cryptography` by running `pip install cryptography` and you should be also set. (You also can safely uninstall `ecdsa` as well).

**Comment by shea256** [comment]
Cryptography does not support secp256k1 (the curve that bitcoin uses). I
submitted an issue and requested it be added and they are currently
considering.

What version required and used ecdsa for ec algorithms? I will probably
switch to that one.

On Thursday, April 23, 2015, Mark Adams <notifications@github.com> wrote:

> Previously, PyCrypto was required for RSA and ecdsa was required for EC
> algorithms. Back in December, we switched to using cryptography instead
> of those libraries because it provided both sets of algorithms (RSA and EC)
> in a single library and also had better performance.
>
> Please make sure you have installed cryptography by running pip install
> cryptography and you should be also set. (You also can safely uninstall
> ecdsa as well).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jpadilla/pyjwt/issues/151#issuecomment-95773261>.
>


-- 

*RYAN SHEA*   *CO-FOUNDER, ONENAME*

*onename.com/ryanshea <http://onename.com/ryanshea> *

*650-564-7432 <650-564-7432>*

**Comment by mark-adams** [comment]
@shea256,

PyJWT will work fine with both `cryptography` and `ecdsa` installed if you need to use `ecdsa` for other purposes (bitcoin, etc.). You are not required to uninstall it. Its just reccomended if that's the only reason you have it.

**Comment by shea256** [comment]
Hm. Let me clarify. As you can see above, I used ECDSA for generating PEMs, but PyJWT simply won't accept them.

**Comment by mark-adams** [comment]
Thanks for clarifying!

Back in December, we switched from using `ecdsa` to `cryptography` for performing the signing and verification of tokens using EC algorithms. That means for all releases since December, if `cryptography` was not installed, you would receive a `NotImplementedError('Algorithm not supported')`

In order to use EC algorithms with PyJWT, you need to run `pip install cryptography` so that the proper library can be installed.

**Comment by shea256** [comment]
Mark I don't think we're understanding each other.

I have both cryptography and ecdsa installed and have always had both installed.

**Comment by shea256** [comment]
Can you please look at my code above and see if you can run it? Maybe that will help us get on the same page.

**Comment by shea256** [comment]
And strangely it's working for me again. I honestly have no idea what happened (my `pip freeze` is the same as it was before).

**Comment by dukedougal** [comment]
It would be good if the error suggested that the problem might be that "cryptography" is now needed instead of PyCrypto.
