### ISSUE TITLE
JTI header support

### ISSUE THREAD

**Issue by foxx** [jpadilla/pyjwt#194]
It seems that there is no official support for a `JTI` header. Are there any plans to add this? Couldn't seem to find any other related issues or PRs.

**Comment by mark-adams** [comment]
Hi @foxx,

I'm assuming that you're referring to the [JTI claim](https://tools.ietf.org/html/rfc7519#section-4.1.7) that can be used to provide a unique identifier for the JWT in order to prevent replay attacks?

Nothing PyJWT will stop you from using this header if you want to. However, by definition, this header requires you to keep track of previously seen JTIs in order to be useful, its usage is outside the scope of the library and better served by your application.

For instance, your application might use a Redis or Memcache database to set a key value matching the JTI whenever the token is seen. If your application receives the same token again, it can prevent replay by simply looking up the JTI in the database and verifying that it is not present (meaning it has not been seen before). Obviously, something like this is outside the scope of a library to parse and verify JWTs (like PyJWT).

However, nothing stops you from setting the `jti` claim on a token or retrieving the `jti` from a decoded token. I hope that answers your question.

**Comment by foxx** [comment]
Thank you for the details reply @mark-adams, I was slightly thrown off by the [docs][1] stating that PyJWT supported a set of registered claims (which did not include JTI), but I understand now why `JTI` isn't shown as supported, even though PyJWT allows any payload/header keys. Sorry for the wasted time on this!
