### ISSUE TITLE
Does PyJWT cache the RSA public key loading?

### ISSUE THREAD

**Issue by tarzanjw** [jpadilla/pyjwt#204]
I have a RSA public key in PEM format, should I load it into RSA key and pass it to `jwt.decode` to avoid key parsing many times? Or just pass the string value and PyJWT has cached it already?

**Comment by mark-adams** [comment]
@tarzanjw Currently, we don't cache the parsed key, however... if you parse the key yourself using `RSAAlgorithm.prepare_key()`, you can reuse that result as an argument to `jwt.encode()` and avoid having to reparse.

Generally, parsing should be pretty quick though since `cryptography` uses OpenSSL.

**Comment by tarzanjw** [comment]
Thanks for reply
