### ISSUE TITLE
Allow a list of valid audiences to be configured

### ISSUE THREAD

**Issue by jobec** [jpadilla/pyjwt#205]
A JWT token can contain multiple audiences.

But, it would be nice if you could also specify a list of valid audiences for `audience` in `jwt.decode()`.

Example:

``` Python
options = {
    'verify_signature': True,
    'verify_exp': True,
    'verify_nbf': True,
    'verify_iat': True,
    'verify_aud': True,
    'verify_iss': True,
    'require_exp': False,
    'require_iat': False,
    'require_nbf': False
}

payload = jwt.decode(
    jwt_value,
    key=self._public_key,
    verify=True,
    audience=["audience_1", "audience_2"],
    issuer="SomeIssuer",
    options=options,
)
```

**Comment by mark-adams** [comment]
I think the reason this wasn't implemented originally was based primarily on the typical use case.

For instance, a normal JWT use case is for an identity provider (the issuer) to issue a token to a user that is valid for service A, service B, and service C. When service A receives a request containing the token, it doesn't care about whether or not service B or service C are in the list, only that it (service A) is in the list of audiences on the token.

For that reason, I think most use cases only require validating that a single audience is in the list.

**Comment by AndrewJHart** [comment]
I actually agree with @jobec because in our instance - using JWT for oauth - we have 2 different audiences. One audience is a single page app that once authenticates with users service has a unique client_id & audience. But, if a service needs to communicate with another service - when it makes a request to the users service it will have a different audience/client_id. Therefore, since we can only set one audience - we're limited to either allowing only the single page app to make API requests to services or limited to allowing only services to make requests to other services. 

I would be happy to work on this if you would give it the ok - I don't think openid-connect and oauth flows were originally considered when designing the audience check for this library... 

Thanks,

**Comment by codervinod** [comment]
@mark-adams We have a use case where identity provider issues tokens to different clients. We have a single API which authenticates via JWT and hence we need to absorb a list of audience. I will send a pull request regarding this feature later today. It would be helpful if you can merge it.
