### ISSUE TITLE
TypeError in compat.py with Python 3.2.5

### ISSUE THREAD

**Issue by shamdan** [jpadilla/pyjwt#206]
File "/usr/local/site-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
    File "/usr/local/site-packages/jwt/api_jws.py", line 115, in decode
    key, algorithms)
    File "/usr/local/site-packages/jwt/api_jws.py", line 177, in _verify_signature
    if not alg_obj.verify(signing_input, key, signature):
    File "/usr/local/site-packages/jwt/algorithms.py", line 138, in verify
    return constant_time_compare(sig, self.sign(msg, key))
    File "/usr/local/site-packages/jwt/compat.py", line 50, in constant_time_compare
    result |= ord(x) ^ ord(y)
    TypeError: ord() expected string of length 1, but int found

This is what I get when using `decode`. I am using [pypy3 v2.4](http://doc.pypy.org/en/latest/release-pypy3-2.4.0.html)

**Comment by jpadilla** [comment]
We're not testing against pypy, so I'm not sure what our support for it might be. A pull request adding those to Tox/Travis is welcome. We can see how to move forward from there.

**Comment by shamdan** [comment]
I ended up upgrading pypy version which now supports Python 3.3. Thanks

**Comment by efossier** [comment]
@jpadilla PyJWT doesn't support python 3.2 because hmac.compare_digest was added in 3.3, it therefore falls back to your python2 reimplementation of compare_digest which does an ord() on the characters before comparing them. This works in python2 but in python3 zip() on bytes objects returns integers giving the error above. 

I fixed this in my project by re-implementing hmac.compare_digest without the ord calls again and monkey patching that method onto hmac.compare_digest so PyJWT finds it.

I also created this PR to fix this in master if you are interested: https://github.com/jpadilla/pyjwt/pull/237
