### ISSUE TITLE
RS256 supported?

### ISSUE THREAD

**Issue by kevart** [jpadilla/pyjwt#208]
`encoded = jwt.encode(payload, 'secret', algorithm='RS256')`

NotImplementedError: Algorithm not supported

PyJWT==1.4.0

**Comment by jpadilla** [comment]
You'll need to install `cryptography`. [Docs](https://pyjwt.readthedocs.io/en/latest/installation.html#cryptographic-dependencies-optional).

**Comment by kevart** [comment]
_NotImplementedError_ is confusing here. It is implemented, just needs another dependency.

**Comment by mark-adams** [comment]
Possibly. If you look at the implementation, when the dependency is not installed, the code related to RSA is literally not executed so `NotImplementedError` is actual true because PyJWT does not have any idea what RS256 is or how to sign / verify a JWT with it unless you actually have the `cryptography` library installed.

As @jpadilla pointed out, I think this is ok since its explicitly stated in the documentation.

**Comment by kkirsche** [comment]
I have cryptography installed and I'm getting this error with the latest PyJWT, Cryptography and Python 3 version (Python 3.8.5) — really confusing what's going on

**Comment by deifante** [comment]
@jpadilla that solution no longer works. I'm still getting a InvalidAlgorithimError with cryptography and pyjwt installed via pip.
