### ISSUE TITLE
ExpiredSignatureError when `now < exp < utcnow`

### ISSUE THREAD

**Issue by OJFord** [jpadilla/pyjwt#209]
I'm not really sure what's going on here, but if I decode without verifying the `exp` field is quite clearly greater than current UTC:

``` python
>>> jwt.decode(token, key, algorithms=['RS256'])
jwt.exceptions.ExpiredSignatureError: Signature has expired
>>> decoded = jwt.decode(token, key, algorithms=['RS256'], verify=False)
>>> datetime.fromtimestamp(decoded['exp']) > datetime.utcnow()
True
>>> with freezegun.freezetime(datetime.utcnow()):
...     jwt.decode(token, key, algorithms=['RS256'])
...
jwt.exceptions.ExpiredSignatureError: Signature has expired
```

Though it does verify if I freeze time to some time in the past:

``` python
>>> with freezegun.freezetime(datetime.today().date()):
...     jwt.decode(token, key, algorithms=['RS256'])
...
{...}
```

All that I can think is that it may be because the expiry is less than 'actual' time, which is BST (UTC+1), and non-UTC system time is slipping through some how. This issue occurs on multiple (all) machines.

**Comment by mark-adams** [comment]
The `exp` claim is a `NumericDate` as defined by [RFC 7519|https://tools.ietf.org/html/rfc7519#section-4.1.6] which means it is a value representing the number of seconds since 1970-01-01T00:00:00Z UTC. 

The problem in your example case is the usage of `datetime.fromtimestamp()` which takes a unix timestamp and returns a `DateTime` value in *local* time (not UTC).

> Return the local date corresponding to the POSIX timestamp, such as is returned by time.time(). This may raise ValueError, if the timestamp is out of the range of values supported by the platform C localtime() function. It’s common for this to be restricted to years from 1970 through 2038. Note that on non-POSIX systems that include leap seconds in their notion of a timestamp, leap seconds are ignored by fromtimestamp().
- https://docs.python.org/2/library/datetime.html#datetime.date.fromtimestamp
