### ISSUE TITLE
Should 'verify=False' during decode also imply _validate_claims?

### ISSUE THREAD

**Issue by aventurella** [jpadilla/pyjwt#217]
When decoding the token, `verify` here ensures the signature passes:
https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwt.py#L63

However weather or not we want the signature verified spills over into weather or not we want the claims verified.

https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwt.py#L73

The 2 use cases to me seem like distinct options, aka bypass the signature verification but still do the additional claim checks.

In my particular use case I have an API that I am acting as a reverse proxy for. So while the user get's a JWT, I don't have the signature, so I cannot verify it, rightfully so, the actual API destination will handle that. If the user's JWT is expired however it would save me an http request to get a rejection I can check easily.

**Comment by mark-adams** [comment]
If I'm understanding you correctly, you're saying that you basically want your reverse proxy layer to be able to reject the request if the token's expiration is invalid by using the token's `exp` claim without performing signature verification as a short-circuit to avoid having to pass the request to the application. Is that correct?

Many applications choose to solve this by consolidating their logic around authentication in a single location (in your case: either the reverse proxy layer or the application layer; not both). This approach avoids complexity since any rejection of the token must originate in only a single block of code. One possible solution would be to move all of your token validation logic (including the verification of the signature) into the reverse proxy layer and simply add one or more additional HTTP header values containing the desired claims to be forwarded to the application. The application could then simply rely on those header values passed by the proxy. In that case, all invalid tokens regardless of reason could be caught at the reverse proxy layer and never reach the application at all.

All of that being said, a potential solution would be to change the API of the library so that by default verify=False does not validate any of the standard claims unless you pass options explicitly.
