### ISSUE TITLE
Implementation not compatible with others

### ISSUE THREAD

**Issue by skomak** [jpadilla/pyjwt#248]
Hi,

Please correct me if I am wrong but I think that using python dicts {} is not a good idea because they have no order so if I try to set up headers:

```
>>> a = {"typ":"JWT","alg":"HS256"}
>>> a
{'alg': 'HS256', 'typ': 'JWT'}
```

The keys are being sorted. In this case of course base64 will be different and HMAC also so in current situation it is incompatible with other implementations of JWT, for example with Firebase in PHP where dicts are not changing the order.

For example in your implementation:

```
>>> jwt.encode({"user":"admin", "iat":1490284641, "exp":1490284671}, "1234567890", headers={"typ":"JWT","alg":"HS256"})
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0OTAyODQ2NDEsInVzZXIiOiJhZG1pbiIsImV4cCI6MTQ5MDI4NDY3MX0.DW6tX95u1bnCmE4KI57Sd3YoDy-9h0jRfD6Iq710mkA'
```

and decoded values are with changed order so the HMAC also:

```
{"alg":"HS256","typ":"JWT"}
{"iat":1490284641,"user":"admin","exp":1490284671}
```

In PHP:

```
php -r 'require __DIR__ . "/vendor/autoload.php"; use \Firebase\JWT\JWT; $key="1234567890"; $token=array("user" => "admin", "iat" => 1490284641, "exp" => 1490284671); $jwt = JWT::encode($token, $key); print_r($jwt);'
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE0OTAyODQ2NDEsImV4cCI6MTQ5MDI4NDY3MX0.-4t8mic0KewXh0e7kJ5QWqyxzQnIZ8u0YjNa1UppNtQ
```

The order remains the same:

```
{"typ":"JWT","alg":"HS256"}
{"user":"admin","iat":1490284641,"exp":1490284671}
```

Cheers,
Dawdi

**Comment by mark-adams** [comment]
The HMAC is not affected because it is performed against the serialized JSON string representation of the dict. Whenever a JWT is created, the Python `dict` is serialized into a JSON string which is hashed as part of producing the signature. When you receive and verify a JWT, the same JSON string (which is identical no matter what platform you are on) is hashed as part of verifying the signature.

The differences in ordering for data structures like `dict` doesn't come into play until after the signature is verified and the JSON is deserialized and at this point, HMAC doesn't matter anymore.

However, you are correct that different languages / frameworks have different guarantees surrounding ordering of the keys in their different data structures. However, this doesn't matter with regards to Python / JWT because the dictionary is serialized into a JSON string before the signature is computed.

**Comment by skomak** [comment]
Python and PHP implementations give different results when providing the same data, please look above in presented examples.

It should be the same but it isn't, and as far as I know even JSON representation in Python doesn't guarantee the order since it is still saved as dicts.

The signature difference comes from this order differences as i checked it manually.

**Comment by mark-adams** [comment]
Yes, they do give different results and that is completely ok. The spec
does not require that the claims be ordered in any specific way prior to or
during serialization. The spec only requires that any JWT generated by one
implementation is able to be verified and decoded by another unless the
claimset has been modified.

The fact that some implementations choose to order their JSON keys in a
particular manner is not required behavior and doesn't impact the signature
verification because the payload that is signed is simply a string and
there is no concept of keys until the payload is deserialized which happens
after verification is complete.

As far as I know, all of the existing JWT are interoperable (tokens created
with one library can be verified with any other successfully).

If you have an example of a JWT that is created using one library and fails
signature verification in another library, I would definitely be interested
in seeing that.

**Comment by skomak** [comment]
You are right, Python JWT and PHP JWT (Firebase implementation) were able to verify each other signatures. It just was misleading for me as I thought that they should provide exactly the same output when generating signatures.
