### ISSUE TITLE
name clash

### ISSUE THREAD

**Issue by davidedelvento** [jpadilla/pyjwt#282]
Thanks to [this bug in pip](https://github.com/pypa/pip/issues/4625), installing pyjwt and jwt at the same time causes a whole lot of issues with no warning whatsoever to the poor user. Please see https://github.com/pypa/pip/issues/4625 and https://github.com/GehirnInc/python-jwt/issues/9 for details.

And pretty please consider talk with the author of the other package and agree on a unique namespace.

**Comment by mark-adams** [comment]
This is one of the unfortunate parts of working in Python and is rather hairy to deal with. I think it's difficult to solve because changing either library is a breaking change. I think the occurrence you're talking about is fairly rare though I'd be interested in seeing numbers of times projects require both libraries.

Because of the rarity, I don't really see how either project would see this as a big enough deal to actually make a change but I appreciate you bringing it up.

Thoughts @jpadilla ?

**Comment by davidedelvento** [comment]
@mark-adams thanks for your consideration. 

I understand why you don't want to make a breaking change, not even with a deprecation period during which both old and new name may be available, even though I think that in the long term this would be the most desirable outcome (in some environment people may want to use both packages).

Frankly, I have been seriously disappointed by the discussion about this [issue in pip](https://github.com/pypa/pip/issues/4625). As a workaround, would it be possible for you to add some logic in the install which pip executes? Something like

```
try:
    import the-other-jwt
    # success, bad: the-other-jwt is already installed
    abort install with a message explaining the situation
except ImportError:
    # good, other package is not present
    proceed with install
```

IMHO this will be great improvement compared to clobbering, and leave to the user the informed decision (i.e. picking one of the two packages, not installing or uninstalling the other), as opposed to a broken environment.

Thanks again!

**Comment by jpadilla** [comment]
Agree with @mark-adams . Thanks for bringing this up, but will close for now.
