### ISSUE TITLE
decoding a payload that is a list

### ISSUE THREAD

**Issue by david-jana** [jpadilla/pyjwt#326]
Hi, I'm using pyjwt with an api that accepts and returns jwt tokens.  I ran across a case where the api returned a token where the payload string encoded a list rather than a map, and the pyjwt decode() function resulted in "jwt.exceptions.DecodeError: Invalid payload string: must be a json object". 

see https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwt.py#L84-L85

 I'm wondering if encoding a list in the payload string violates the JWT protocol, and if not, whether there is (or should be) a way to handle this in pyjwt.  At the least, the error message seems misleading since if json.loads() is successful, I would think the string should count as a json object.

thanks

**Comment by vimalloc** [comment]
I believe that the JWT spec requires the items to be a dict, due to all the documented claims. I assuming you are trying to encode a JWT that looks something like `['foo', 'bar', 'baz']`, is that right? Instead, you should do something like `{'items': ['foo', 'bar', 'baz']}`.

Maybe the wording of that exception could be updated to be less confusing.

**Comment by david-jana** [comment]
My outgoing messages are all dicts, so no problem encoding.  It's the incoming message from making a third party api call that I'm trying to decode where the payload is just the list instead of embedding the list as the value of a key in a dict as in your suggestion.  I'll raise this issue with the third party and if I need to I'll just use a custom decode function that doesn't block such cases.  Thanks.
