### ISSUE TITLE
Does pyjwt support the jti claim (nonce used to prevent replays)?

### ISSUE THREAD

**Issue by mw44118** [jpadilla/pyjwt#339]
I want to make sure a reset-password link can't be used more than once.

I'm setting an "exp" key to make it expire after a fixed amount of time.  I see there is a "jti" claim described in the spec, where each JWT would have a unique key, and I could verify that I've never seen this before.

Does pyjwt have this built-in?

If not, I can still add a "jti" key that points to a uuid.uuid4() value and then check after I decode the string.

Would you want a patch that extracts this jti key?

Thanks for writing this package, by the way!  It is great.

**Comment by mark-adams** [comment]
Thanks!

In the case of some claims that have a very clear method of validation (like `nbf` and `exp`), we have built-in support in the library since it's easy to implement those. For `jti`, there's a lot of application-specific concerns involved that might differ between applications. For instance, if you are running a single instance of a web app, it might be easy to just have an in-memory set that stores previously seen `jti` values but should that set be persisted somehow if the app is restarted? If so, how? If your application runs multiple instances for redundancy, these instances will probably want to share that state somehow. Should that be via Redis, a database of some sort, or maybe an external service call of some sort?

As you can see, there's a lot of application-specific complexity involved in deciding how to handle `jti` claims so we opt'd for the simplest solution: let application developers handle it themselves. Currently, you can simply call `claims =jwt.decode(token, secret)` and PyJWT will return a dictionary of the claims. From there, you can take the `claims['jti']` and perform any special logic that you wish to make sure that you aren't processing duplicate tokens.

I hope that helps!

**Comment by mw44118** [comment]
I agree with all that; maybe the right thing to do is just have that paragraph in the docs, so that browsers like me don't ask this question again and again :)

I'll try to send a patch for the docs soon.
