### ISSUE TITLE
Unable to decode token

### ISSUE THREAD

**Issue by rahulchowdhuryce** [jpadilla/pyjwt#481]
I am given a JWT which does not contain any dots. I read somewhere that the typical format of a JWT is 3 pieces of string concatenated with 2 dots in total. Using PyJWT when I try to decode the token, I am getting the below error -

```
Traceback (most recent call last):
  File "/home/neelanjana/.virtualenvs/athena_env/lib/python3.7/site-packages/jwt/api_jws.py", line 180, in _load
    signing_input, crypto_segment = jwt.rsplit(b'.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/neelanjana/.virtualenvs/athena_env/lib/python3.7/site-packages/jwt/api_jwt.py", line 84, in decode
    payload, _, _, _ = self._load(jwt)
  File "/home/neelanjana/.virtualenvs/athena_env/lib/python3.7/site-packages/jwt/api_jws.py", line 183, in _load
    raise DecodeError('Not enough segments')
jwt.exceptions.DecodeError: Not enough segments

```

However, when I put the same token on jwt.io, it gets decoded and I am able to see the complete dictionary. Is What am I missing?

Here is my code -
```python
import jwt

a = "someToken"
print(jwt.decode(a))
```

Attaching a pastebin link to the token [here][1] since it is too long to put here.

P.S. I am not married to the idea of using pyjwt. If any other library can decode it it's all the same for me.

  [1]: https://pastebin.com/L7F6DMR2

**Comment by vimalloc-mavenlink** [comment]
In this case all http://jwt.io is doing is base64 decoding your string to turn it back into a JSON object. It isn't doing any verification to make sure the token was not tampered with because there is not enough information available in your "token" for that. In fact, the "token" you have is *not* a JWT, and should not be treated as such. Without the signature in the third segment of the JWT you cannot be sure that token has not been maliciously tampered with.

You can read about the structure of a JWT directly on jwt.io: https://jwt.io/introduction/

**Comment by dimaqq** [comment]
I've pulled your paste and looked inside, it's not a JSON Web Token:
```
> base64 -d < ~/Downloads/token.b64.txt| head -c 100
{"course":{"id":"fCn9lomkZIqjUfh0MCU2lICH7dUbEEO0","originalId":null,"author":"aid|9f5c1067-f2b6-4b2⏎

> base64 -d < ~/Downloads/token.b64.txt| tail -c 100
true,"key":"assets/rise/fonts/Merriweather-Black.woff","style":"normal","weight":"900"}],"media":[]}⏎

```

**Comment by dimaqq** [comment]
I vote to close this issue :D
