### ISSUE TITLE
jwt.encode returns str instead of bytes in 2.0.0a1

### ISSUE THREAD

**Issue by the-papi** [jpadilla/pyjwt#529]
Latest pre-release 2.0.0a1 brings change of function jwt.encode, that doesn't return bytes as in release 1.7.1, but str. Is it a bug or will it stay that way?

I am asking, because it breaks https://github.com/SimpleJWT/django-rest-framework-simplejwt and I need to know where the fix should be done.

## Expected Result

`jwt.encode` to return `bytes`

## Actual Result

`jwt.encode` returns `str`

## Reproduction Steps

```python
import jwt

encoded = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')
print(encoded)
```

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": "3.1"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "5.9.1-arch1-1",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "2.0.0a1"
  }
}
```

**Comment by jpadilla** [comment]
I was not able to reproduce this https://repl.it/repls/JampackedIvoryHack#main.py

https://github.com/jpadilla/pyjwt/pull/513

Although we do need to update docs https://github.com/jpadilla/pyjwt/pull/521

**Comment by PapiCZ** [comment]
Sry... i wapped it. I expect to return bytes instead of str (as in 1.7.1).

**Comment by jpadilla** [comment]
It is in fact an expected change.

**Comment by rudyryk** [comment]
> It is in fact an expected change.

I'd disagree, this is strong backward incompatibility change, which is not expected in such "core" library. Usually it's used at the very utility level and could break everything one day after occasional update.

Since the method name is unchanged, the only good approach here is to return proxy wrapper which will not break on `.decode('utf-8')` for example (because `str` has no decode). And show warning for a while, 6-12 months until most of codebase is updated or pinned to older version, like 1.7.1

It's often specified simply `pyjwt` in dependencies without version restrictions.

**Comment by jpadilla** [comment]
I appreciate the feedback, thanks.

While I do agree that I could've planned out a whole series of releases with deprecation warnings, compatibility layers, and the whole lot, I ultimately decided against that because that does take time and energy to execute. I knew I wanted to make breaking changes, I knew I wanted to add new features, address bugs, etc so I decided to just release new major version.

> It's often specified simply pyjwt in dependencies without version restrictions.

I'd say this is part of the problem, one I shouldn't have to be necessarily constrained by. I'd argue that everyone should just be pinning the versions of their dependencies down to specifics, going from one version to another(specially major versions) isn't a thing to be taken lightly, it needs some level of due diligence either by computers(CI, tests, automation, etc) or humans(docs, release notes, etc).

Anyways, something I'll continue keeping in mind for future releases. ✌️

**Comment by rudyryk** [comment]
@jpadilla I do agree, that pinning versions is a better practice than specifying version-less dependency. But also Python community often praise backwards compatibility.

What I meant is actually simply return from the new `jwt.encode()` not a plain `str` but something like:

```python
import warnings

class BytesCompatStr(str):
    def decode(self, encoding='utf-8', errors='strict') -> str:
        warnings.warn(
            "jwt.encode returns `str` since 2.0 not `bytes`,
            please update your calls"
        )
        return self
```

and then `return BytesCompatStr(str_value)`. This won't cover 100% cases but probably more than 90%.

**Comment by rudyryk** [comment]
@jpadilla And also I'd suggest to highlight API changes for 2.0 on the main README.md, now it's implicit (I didn't track if there are other changes).

And thank you for the awesome library with plain simple API. I hate to be the criticising guy but I got unexpected server crashes recently, that forced me to respond :)
