### ISSUE TITLE
empty strings for issuer and audience are treated as "not present"

### ISSUE THREAD

**Issue by wbolster** [jpadilla/pyjwt#55]
Parts of the current code such as this snippet:

``` python
issuer = kwargs.get('issuer')
if issuer:
    if payload.get('iss') != issuer:
        raise InvalidIssuer('Invalid issuer')
```

treat an empty string as issuer, i.e. `""`, the same as "no issuer specified". Though it's a rather bad practice to use empty strings for these values, this might lead to unexpected results. Changing the test to be `if issuer is None:` fixes this.

The same applies to audience, and possibly more.

**Comment by clintonb** [comment]
This just came back to bite us. We forgot to set the issuer on some of our services. We never realized this because no error was raised during the decode operation. There should not be any special values. The `iss` claim should only be considered valid if its value matches the value passed into the function.
