### ISSUE TITLE
Build Fails After Upgrading to 2.0.0 

### ISSUE THREAD

**Issue by ksong-gib** [jpadilla/pyjwt#600]
My pip build started failing with these error when trying to build the PyJWT-2.0.0:

```
File "/tmp/pip-build-6OkzzA/pyjwt/jwt/__init__.py", line 34
    SyntaxError: Non-ASCII character '\xc3' in file /tmp/pip-build-6OkzzA/pyjwt/jwt/__init__.py on line 34, but no encoding declared; 
see http://python.org/dev/peps/pep-0263/ for details
```

Any reasons to remove the utf-8 encoding header from the 1.7.1 version? Can we add it back as a hot fix?
https://github.com/jpadilla/pyjwt/blob/1.7.1/jwt/__init__.py#L1

Thanks,

Kai

**Comment by jpadilla** [comment]
@ksong-gib do you have steps to reproduce this?

**Comment by rudyryk** [comment]
Before the 2.0 release `.encode()` function returned `bytes` and after 2.0 release it starts returning `str`.

This is backward incompatibility in fact and much of code may become broken because of that.

**1.7.1**: https://github.com/jpadilla/pyjwt/blob/1.7.1/jwt/api_jws.py#L127
**2.0.0**: https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jws.py#L126

Didn't see any warning before and the home page is silent on that, which is kind of confusing.

The workaround for older code is to pin version `pyjwt<2.0`

**Comment by rudyryk** [comment]
Sorry for posting here, seem like this is not relevant, found other thread https://github.com/jpadilla/pyjwt/issues/529
