### ISSUE TITLE
cannot import name 'PyJWKClient' from 'jwt'

### ISSUE THREAD

**Issue by olitomas** [jpadilla/pyjwt#685]
I am getting some sort of conflict error since upgrading to python 3.7 from python 3.5.

I am using djangorestframework-simplejwt. But the conflict seems to be when importing jwt:
cannot import name 'PyJWKClient' from 'jwt' (......../venv/lib/python3.7/site-packages/jwt/__init__.py)

But the weird thing is that sometimes it works (no errors) and sometimes it does not. If I refresh the webpage it seems to be a 50/50 if it works or not.

I reinstalled the virtualenv 100x times and keep making sure that pyjwt is the only jwt package installed in the venv.

My pip freeze:

asgiref==3.4.1
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.6
cryptography==3.4.8
Django==3.2.7
django-ckeditor==6.1.0
django-cors-headers==3.8.0
django-filter==2.4.0
django-js-asset==1.2.2
django-phonenumber-field==5.2.0
django-rest-registration==0.6.4
djangorestframework==3.12.4
djangorestframework-simplejwt==4.8.0
drf-writable-nested==0.6.3
idna==3.2
phonenumbers==8.12.31
pkg-resources==0.0.0
psycopg2==2.9.1
pycparser==2.20
PyJWT==2.1.0
pytz==2021.1
requests==2.26.0
slugify==0.0.1
sorl-thumbnail==12.7.0
sorl-thumbnail-serializer-field==0.2.1
sqlparse==0.4.2
typing-extensions==3.10.0.2
Unidecode==1.3.2
urllib3==1.26.6

Any help would be greatly appreciated!

**Comment by geekypandey** [comment]
sorry to hear that. Which version of `pyjwt` are you using? Sometimes due to multiple python and pip there is confusion in the system. Could you use the following code to get the version info?
```py
import jwt

print(jwt.__version__)
```
Some commands that have come handy to me are:
`python -m pip install ...` instead of `pip install ...` - The pip used is then tied to the python which is used.
`which python` - To get the location of python used. This helps to check whether it is using the virtual environment python or not.

**Comment by bemonio** [comment]
Hi!, check the version of djangorestframework-simplejwt, I had the same problem and I changed it 
from: djangorestframework-simplejwt==4.8.0
to: djangorestframework-simplejwt==4.7.2
