### ISSUE TITLE
The result of encoding is different from the official website（https://jwt.io/）.

### ISSUE THREAD

**Issue by miloira** [jpadilla/pyjwt#718]
The official website result is `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwiZXhwIjoxNTE2MjM5MDIyfQ.Wmw6IKBTkRK0c7qX1E2rEGb8D6cqjnC6l3FFOT4WvOs`

## Expected Result

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwiZXhwIjoxNTE2MjM5MDIyfQ.Wmw6IKBTkRK0c7qX1E2rEGb8D6cqjnC6l3FFOT4WvOs
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwiZXhwIjoxNTE2MjM5MDIyfQ.Wmw6IKBTkRK0c7qX1E2rEGb8D6cqjnC6l3FFOT4WvOs

## Actual Result

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwiZXhwIjoxNTE2MjM5MDIyfQ.Wmw6IKBTkRK0c7qX1E2rEGb8D6cqjnC6l3FFOT4WvOs
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwiZXhwIjoxNTE2MjM5MDIyfQ.JnHKRoQGqK0YgsCft_xowLNQkWOdeJrMeR3I10tVBs4

## Reproduction Steps

```python
import json
import base64
import hmac
import hashlib
import jwt

headers = {"alg":"HS256","typ":"JWT"}

payload = {"id":1,"name":"admin","exp":1516239022}

def jwt_encode(header, payload, key):
    json_header = json.dumps(header,separators=(",", ":"))
    json_payload = json.dumps(payload,separators=(",", ":"))

    header_b64 = base64.urlsafe_b64encode(json_header.encode()).replace(b'=', b'')
    payload_b64 = base64.urlsafe_b64encode(json_payload.encode()).replace(b'=', b'')

    segments = [header_b64, payload_b64]

    sign_input = b'.'.join(segments)

    signature = hmac.new(key.encode(), sign_input,
                         hashlib.sha256).digest()

    signature_b64 = base64.urlsafe_b64encode(signature).replace(b'=', b'')

    segments.append(signature_b64)

    token = b'.'.join(segments).decode()

    return token

print(jwt_encode(headers, payload, 'django-insecure-vgbfyux**xgc2ekt0$v93dnmej#=j5uj#1y%6-noxk5mcgv@o6'))

print(jwt.encode(headers=headers,payload=payload,key='django-insecure-vgbfyux**xgc2ekt0$v93dnmej#=j5uj#1y%6-noxk5mcgv@o6'))
```

## System Information

    $ python -m jwt.help

```
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
PyJWT                     2.3.0
```

This command is only available on PyJWT v1.6.3 and greater. Otherwise,
please provide some basic information about your system.

**Comment by hsupu** [comment]
Could you repeat your test? I got `Invalid Signature` on jwt.io for both your expected & actual result.

**Comment by ilatypov** [comment]
Moving @miloira 's `typ` attribute to the beginning of the `header` dictionary makes both signatures the same `..s4`.  Both @miloira 's code and PyJWT stringify dictionaries without sorting them by keys,

https://github.com/jpadilla/pyjwt/blob/2.3.0/jwt/api_jwt.py#L59
https://github.com/jpadilla/pyjwt/blob/2.3.0/jwt/api_jws.py#L93-L102
https://docs.python.org/3/library/json.html#json.dumps

PyJWT constructs the header with the `typ` element first.

Despite a mailing list message endorsing the insertion order of the `dict` implementation as a guarantee (since 3.6?),

https://news.ycombinator.com/item?id=12460936

I wish sorting the keys for `json.dumps(.., sort_keys=True)` was prescribed with an explicit comparator, but I have not tried this.  Quickly searching online brings up examples on how to sort dictionaries rather than how to make their keys sortable in a prescribed order.

**Comment by MakRude** [comment]
Not sorting the dictionary header keys like @ilatypov uncovered is not necessary to comply with the RFC, but it might be a good idea.

I've faced compatibility issues with other JWT libraries (For instance with https://github.com/golang-jwt/jwt because Go automatically sorts maps when they are converted to JSON strings)

I'm constrained to using Python due to hardware constraints, which is how I came across this issue.
