### ISSUE TITLE
Decoding does not handle the `x5c` header

### ISSUE THREAD

**Issue by fxdgear** [jpadilla/pyjwt#90]
https://github.com/jpadilla/pyjwt/blob/0.4.1/jwt/__init__.py#L353-L355

**Comment by mark-adams** [comment]
This is talked about in Section 4 (JOSE Header) of the JWS specification. However, it is an optional feature for implementation since it is not described as "MUST be understood" parameter in the header.

So, the good news is... we're not missing anything mandatory here for us to be a conforming implementation.

**Comment by jpadilla** [comment]
This is up for grabs to anyone who wants to take a stab at implementing whatever is needed and including tests.

**Comment by fxdgear** [comment]
I'll attempt to take a stab at this since I need it, will start on it soon (unless someone gets to it before me)

**Comment by fxdgear** [comment]
so i talked to some of the guys in the #cryptography-dev channel on IRC. It's lead to me creating this issue in the cryptography repo: https://github.com/pyca/cryptography/issues/1660

**Comment by mark-adams** [comment]
Since x5c is part of JWK, we'll probably implement this as part of #144 and include this as part of the 2.0.0 since it looks like it'll involve implementing most of JWK. 

I don't think its really feasible to implement this separately from our 2.0.0 release so I'm going to go ahead and close this so we can track progress on #144
