### ISSUE TITLE
Decoding performance issue

### ISSUE THREAD

**Issue by jeffjzx** [jpadilla/pyjwt#98]
Hi, in my implementation i have to decode the same JWT token twice. First one is used in decorator to verify authentication and the second one is used in main function just to extract user information. Say i add "verify=False" in my second one, will this gain a little bit performance benefit?

**Comment by wbolster** [comment]
Yes, though it's arguably better to decode only once in your decorator and store the result in a "request scoped" storage, e.g. `flask.g` or something like that.

**Comment by jeffjzx** [comment]
@wbolster
Thank you, i have considered that, but say if i have several servers run the same web application and have the load balancer will redirect user to corresponding server. My plan is to use Redis as distributed memory cache to save user token in order to synchronize all the servers. However in case of flask.g it only save user information locally.

This is my first time designing a complicated application, i'm not sure if it follows common practice. Please let me know if design has any potential pitfalls.

**Comment by rjprins** [comment]
@jeffjzx 
Generally the token enables stateless server authentication. Meaning that it's not necessary to save the token in Redis or something similar. However if your main function is in an entirely different process than the token authentication, then there a few things you could do:
1. Pass on the token to the main function process, and decode it again.
2. Pass on the decrypted token information to the main function process (perhaps as a specific header, if the set-up is proxy-like)
3. Save the decrypted token information in a database, and then retrieve it in the main function.

A database call may be just as expensive as decrypting the token twice, it's hard to say without actual numbers.
If the authentication process is separate from your main process, than it makes a lot of sense to only pass on the payload, and hide authentication implementation details (such as using JWT) from the main process.

**Comment by wbolster** [comment]
@jeffjzx  Proxying (perhaps through a load balancer, perhaps just nginx reverse proxy) is very common, and in those cases you pass the token in a HTTP header in each request, and the server verifies the token for every request. As @rjprins said, there is _no state_ involved, so no need for redis/database/globals.

As I understood it, your original question was about decoding a JWT twice when handling a request. I assumed the first time would be something like a `@login_required` decorator, and the second time you actually need some data field from the JWT. In that case my suggested approach works just fine: in the `@login_required` decorator (or similar; this depends on your web framework) you decode and verify the token, and you store the decoded result in a request-scoped "global". For flask `flask.g` would be the obvious choice. Within your view function (or "request handler"; depends on your web framework), you can simply access the previously decoded and verified data.  And since this data is kept in a request-scoped variable, it will be gone after the response has been sent back to the client, so the next request handled by your application will be completely independent (no shared state).

**Comment by jeffjzx** [comment]
Thanks guys! I'll adapt your suggestion in my implementation
